Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,6 +23,7 @@ jobs:
       - name: Deploy API to server
         run: |
           rsync -avz --delete ./MyStreamHistory.API/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/MyStreamHistory.API/
+          rsync -avz --delete ./docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/
 
       - name: Restart API on server
         run: |
@@ -38,11 +39,18 @@ jobs:
       - name: Wait for API to be healthy
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-          while ! curl -s http://localhost:5000/health; do
-            echo "Waiting for API to be healthy..."
-            sleep 5
+          end=$(( $(date +%s) + 60 ))  # Устанавливаем время окончания через 60 секунд
+          while [ $(date +%s) -lt $end ]; do
+            if curl -s http://localhost:5000/health; then
+              echo "API is up and running!"
+              exit 0
+            else
+              echo "Waiting for API to be healthy..."
+              sleep 5
+            fi
           done
-          echo "API is up and running!"
+          echo "Error: API did not become healthy in time!"
+          exit 1
           EOF
 
       - name: Finish deployment
